### ISSUE TITLE
Trying to send XLM from an albedo account with IOS and the transaction is not processed

### ISSUE THREAD

**Issue by 0001jb** [stellar-expert/albedo#51]
Hello,

I am trying to send XLM from albedo to a Bitstamp account.

When I confirm the transaction, the status of the transaction says "submitting transactions".

Unfortunately, the transaction is never processed and it is always saying "submitting transactions".

It could be due to a pop-up issue with IOS but I am not sure.

Do you know what I could do to finalize the transfer?

Thanks a lot!

**Comment by orbitlens** [comment]
Hello!

I reproduced the issue you pointed out and we started working on this Safari-specific problem. 
Unfortunately, fixing this will take some time.

In the meantime, you can enable popup windows in your browser following this [walkthrough](https://www.isc.upenn.edu/how-to/configuring-your-web-browser-allow-pop-windows). This should fix the problem.

Sorry for the long response. We are overwhelmed with support requests. And I apologize for the inconveniences.

**Comment by 0001jb** [comment]
Awesome, the issue has been resolved!  Thanks a million!
