### ISSUE TITLE
Issue Transaction Sign with CreateClaimableBalance Operation

### ISSUE THREAD

**Issue by agenio** [stellar-expert/albedo#59]
Hello,

we have just found an issue with albedo parsing a transaction XDR containing a CreateClaimableBalance operation.

Albedo show a wrong claimant destination address, you can view an example in the image below:
![image](https://user-images.githubusercontent.com/4463053/120928074-7b185480-c6e3-11eb-803a-e90255dfc14f.png)

If needed I can post also the XDR transaction string

**Comment by orbitlens** [comment]
Fixed. Thanks for the heads up.

**Comment by agenio** [comment]
Tested and I confirm the fix. Thank you

**Comment by satoshi0x** [comment]
https://stellar.expert/explorer/public/account/GDBNVR7CK5J3UPYPE74TTNZYGESWBDC77FEEHLWJ6N5I5C33SYBO75LD?filter=trades&order=desc

This address has a lot of KTHOUSE. Is this a mistake created by the Albedo bug?
