### ISSUE TITLE
Detect when user close browser tab without taking any action on intent-action-view

### ISSUE THREAD

**Issue by ralphilius** [stellar-expert/albedo#60]
This is useful when integrating with Albedo, so that we could handle this case.

**Comment by orbitlens** [comment]
Hello, 

Sorry for the late response. I missed the notification. 
I double-checked and it looks like Albedo always responds with `actionRejectedByUser` (code -4) error when the Albedo confirmation window/tab is closed. You can check it here for example: https://albedo.link/playground?section=public_key

Could you please provide more context on this problem? What browser are you using? Maybe it's an iframe-embedded integration case built specifically for the StellarQuest?

**Comment by ralphilius** [comment]
Hi @orbitlens,

I was trying to add Albedo to Stellar Laboratory for transaction signing. When debugging, I couldn't get any `actionRejectedByUser` when I just closed the confirmation tab. You can try with the latest code from this repo: https://github.com/stellar/laboratory

**Comment by orbitlens** [comment]
Ok, looks like I found the root of the problem. Now it works flawlessly with the Laboratory on my end.
Could you please check it on your side?

**Comment by orbitlens** [comment]
@ralphilius Did you have a chance to check whether everything works on your side now?

**Comment by ralphilius** [comment]
I didn't have a chance to take a look yet. Could you explain what action I
should take on my side to make it work?

**Comment by orbitlens** [comment]
@ralphilius No need to take any actions. I checked on https://laboratory.stellar.org/ with several browsers on different platforms and it worked flawlessly.

**Comment by ralphilius** [comment]
@orbitlens Confirmed. When closing the tab, it shows an error in Lab UI.
