### ISSUE TITLE
Support Futurnet integration

### ISSUE THREAD

**Issue by PlamenHristov** [stellar-expert/albedo#91]
I've noticed that the wallet supports only testnet and mainnet, but not futurenet. Are there plans to provide support for futurenet, given it's the only "test" network that allows for testing Soroban contracts?

**Comment by orbitlens** [comment]
> I've noticed that the wallet supports only testnet and mainnet, but not futurenet. Are there plans to provide support for futurenet, given it's the only "test" network that allows for testing Soroban contracts?

Hey Plamen,
We are still in process of adding smart contracts support to Albedo. Once it is finished, you will be able to interact with smart contracts on the testnet. Futurenet is too volatile, and we cannot properly support all new Futurenet functions in production mode.
